CREATE USER ATOMSKILLS IDENTIFIED BY ATOMSKILLS
DEFAULT TABLESPACE USERS QUOTA 100M ON USERS
TEMPORARY TABLESPACE TEMP QUOTA 10M ON TEMP;

GRANT CREATE SESSION TO ATOMSKILLS;
ALTER USER ATOMSKILLS QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO Atomskills;
grant DELETE ANY TABLE to ATOMSKILLS;
grant EXECUTE ANY PROCEDURE to ATOMSKILLS;
grant CREATE ANY VIEW to ATOMSKILLS;
grant COMMENT ANY TABLE to ATOMSKILLS;
grant DROP ANY PROCEDURE to ATOMSKILLS;
grant ALTER ANY TABLE to ATOMSKILLS;
grant ALTER ANY SEQUENCE to ATOMSKILLS;
grant UPDATE ANY TABLE to ATOMSKILLS;
grant ALTER ANY TRIGGER to ATOMSKILLS;
grant DROP ANY VIEW to ATOMSKILLS;
grant CREATE VIEW to ATOMSKILLS;
grant DEBUG ANY PROCEDURE to ATOMSKILLS;
grant CREATE ANY TABLE to ATOMSKILLS;
grant CREATE ANY SEQUENCE to ATOMSKILLS;
grant CREATE SEQUENCE to ATOMSKILLS;
grant CREATE TABLE to ATOMSKILLS;
grant SELECT ANY SEQUENCE to ATOMSKILLS;
grant CREATE ANY PROCEDURE to ATOMSKILLS;
grant CREATE PROCEDURE to ATOMSKILLS;
grant CREATE MATERIALIZED VIEW to ATOMSKILLS;
grant DROP ANY TABLE to ATOMSKILLS;
grant DROP ANY SEQUENCE to ATOMSKILLS;
grant CREATE ANY TRIGGER to ATOMSKILLS;
grant DROP ANY TRIGGER to ATOMSKILLS;
